[package]
name = "Robot36Encode"
version = "0.1.5"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "^1.1"
image = "0.21"
wfd = "0.1.7"
num = "0.2"
hound = "3.4.0"
bindings = { path = "bindings" }